version: '3.8'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ".:/var/www/html"